### ISSUE TITLE
How to install Ciara on HPC cluster using conda? I tried using conda skeleton, it didnt work

### ISSUE THREAD

**Issue by elissonlopes** [ScialdoneLab/CIARA#1]
PackagesNotFoundError: The following packages are not available from current channels.

**Comment by gabrielelubatti** [comment]
For installing the python version of CIARA, you can use python -m pip install ciara_python (see here for more info https://github.com/ScialdoneLab/CIARA_python).

**Comment by elissonlopes** [comment]
Sorry I forgot to mention that is the R version.  I need it to run in a cluster. I have to install using conda or something like that but I got this message saying "CIARA is not available on conda channels"

**Comment by gabrielelubatti** [comment]
Yes CIARA is not available on conda. You can install R on the cluster, for example with brew install R (https://brew.sh). Once R is installed you can install CIARA with devtools::install_github("ScialdoneLab/CIARA") or the CRAN version with install.packages("CIARA")

**Comment by elissonlopes** [comment]
There is some problem with R version and Seurat tasks. 
I could finally solve this using this tutorial bellow:
https://www.biostars.org/p/498049/

And Finally I could use devtools.

Thanks for your help Gabriel

**Comment by gabrielelubatti** [comment]
Perfect 👍, happy that now it works!

**Comment by kew24** [comment]
Even though CIARA isn't on conda, it can still be installed through conda from CRAN. Instructions included below for anyone else interested...

```bash
conda create --name ciara r-base=4.1.0
conda activate ciara
conda skeleton cran CIARA
sed -i "s/r-biobase$/bioconductor-biobase/" r-ciara/meta.yaml
sed -i "s/r-base$/r-base=4.1.0/" r-ciara/meta.yaml
conda-build r-ciara
conda install --use-local r-ciara
```

Thanks Gabriele!

**Comment by kew24** [comment]
For future reference, it's now on conda: https://anaconda.org/kew24/r-ciara 
`conda install -c kew24 r-ciara`

If you prefer that I remove this build from my anaconda channel in favor of you uploading it, let me know!
