### ISSUE TITLE
vignette ‘CIARA’ not found 

### ISSUE THREAD

**Issue by Rohit-Satyam** [ScialdoneLab/CIARA#2]
When trying to look for the vignette using `utils::vignette("CIARA")` a warning is thrown

```r
> library(CIARA)
> utils::vignette("CIARA")
Warning message:
vignette ‘CIARA’ not found
```
Besides, can we use CIARA on non-human single cell dataset such as Plasmodium sc timepoint data?

**Comment by gabrielelubatti** [comment]
Did you install CIARA from CRAN (install.packages("CIARA") or from Github (devtools::install_github("ScialdoneLab/CIARA").
The command utils::vignette("CIARA") works with the CRAN version. You can also access the vignette here https://github.com/ScialdoneLab/CIARA/blob/master/vignettes/CIARA.Rmd.
Regarding your second point, yes CIARA can be used on any single cell dataset for which a norm count matrix and knn matrix is available.
Best
